# Generated by Django 5.2.12 on 2026-04-03 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_column='numero', unique=True, verbose_name='Número do Desafio')),
                ('descricao', models.CharField(db_column='descricao', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Desafio PDI',
                'verbose_name_plural': 'Desafios PDI',
                'db_table': 'desafios_pdi',
            },
        ),
        migrations.CreateModel(
            name='Macroprocesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=255, unique=True, verbose_name='Nome do Processo')),
            ],
            options={
                'verbose_name': 'Macroprocesso',
                'verbose_name_plural': 'Macroprocessos',
                'db_table': 'macroprocessos',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(db_column='descricao', verbose_name='Descrição')),
                ('desafio', models.ForeignKey(db_column='id_desafio', on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='riscos.desafiopdi')),
            ],
            options={
                'verbose_name': 'Objetivo PDI',
                'verbose_name_plural': 'Objetivos PDI',
                'db_table': 'objetivos_pdi',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Operacional', 'Operacional'), ('Estratégico', 'Estratégico'), ('Integridade', 'Integridade'), ('Imagem', 'Imagem'), ('Financeiro', 'Financeiro')], db_column='categoria', max_length=50)),
                ('evento', models.TextField(db_column='evento')),
                ('causa', models.TextField(db_column='causa')),
                ('consequencia', models.TextField(db_column='consequencia')),
                ('controles_atuais', models.TextField(db_column='controles_atuais')),
                ('eficacia_controle', models.CharField(choices=[('Forte', 'Forte'), ('Médio', 'Médio'), ('Fraco', 'Fraco')], db_column='eficacia_controle', max_length=50)),
                ('probabilidade', models.IntegerField(db_column='probabilidade')),
                ('impacto', models.IntegerField(db_column='impacto')),
                ('nivel_risco', models.IntegerField(db_column='nivel_risco', editable=False)),
                ('prob_residual', models.IntegerField(db_column='prob_residual')),
                ('imp_residual', models.IntegerField(db_column='imp_residual')),
                ('nivel_residual', models.IntegerField(db_column='nivel_residual', editable=False)),
                ('macroprocesso', models.ForeignKey(db_column='id_macroprocesso', on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='riscos.macroprocesso')),
                ('objetivo', models.ForeignKey(db_column='id_objetivo', on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='riscos.objetivopdi')),
                ('setor', models.ForeignKey(db_column='id_setor', on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='usuarios.setor')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
                'db_table': 'riscos',
            },
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resposta', models.CharField(choices=[('Mitigar', 'Mitigar'), ('Evitar', 'Evitar'), ('Transferir', 'Transferir'), ('Aceitar', 'Aceitar')], db_column='tipo_resposta', max_length=50)),
                ('descricao_acao', models.TextField(db_column='descricao_acao')),
                ('responsavel', models.CharField(db_column='responsavel', max_length=255)),
                ('parceiros', models.TextField(db_column='parceiros')),
                ('data_inicio', models.DateField(db_column='data_inicio')),
                ('data_fim', models.DateField(db_column='data_fim')),
                ('status', models.CharField(choices=[('Não iniciada', 'Não iniciada'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Atrasada', 'Atrasada')], db_column='status', max_length=50)),
                ('observacoes', models.TextField(db_column='observacoes')),
                ('risco', models.ForeignKey(db_column='id_risco', on_delete=django.db.models.deletion.CASCADE, related_name='planos_acao', to='riscos.risco')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'db_table': 'planos_acao',
            },
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_verificacao', models.DateField(auto_now_add=True, db_column='data_verificacao')),
                ('resultados', models.TextField(db_column='resultados')),
                ('acoes_futuras', models.TextField(db_column='acoes_futuras')),
                ('analise_critica', models.TextField(db_column='analise_critica')),
                ('risco', models.ForeignKey(db_column='id_risco', on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='riscos.risco')),
            ],
            options={
                'verbose_name': 'Monitoramento',
                'verbose_name_plural': 'Monitoramentos',
                'db_table': 'monitoramentos',
            },
        ),
    ]
