# Generated by Django 5.2.12 on 2026-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoacao',
            name='observacoes',
            field=models.TextField(blank=True, db_column='observacoes', null=True),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='parceiros',
            field=models.TextField(blank=True, db_column='parceiros', null=True),
        ),
        migrations.AlterField(
            model_name='risco',
            name='eficacia_controle',
            field=models.CharField(choices=[('Inexistente', 'Inexistente'), ('Fraco', 'Fraco'), ('Satisfatório', 'Satisfatório'), ('Forte', 'Forte')], db_column='eficacia_controle', max_length=50),
        ),
    ]
