# Generated by Django 5.2.12 on 2026-04-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0003_seed_pdi_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafiopdi',
            options={'ordering': ['numero'], 'verbose_name': 'Desafio PDI', 'verbose_name_plural': 'Desafios PDI'},
        ),
        migrations.AlterModelOptions(
            name='macroprocesso',
            options={'ordering': ['nome'], 'verbose_name': 'Macroprocesso', 'verbose_name_plural': 'Macroprocessos'},
        ),
        migrations.AlterModelOptions(
            name='objetivopdi',
            options={'ordering': ['codigo'], 'verbose_name': 'Objetivo PDI', 'verbose_name_plural': 'Objetivos PDI'},
        ),
    ]
