# Generated by Django 5.2.17 on 2026-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0007_add_progresso_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoplano',
            options={'ordering': ['-data_hora', '-id'], 'verbose_name': 'Histórico do Plano', 'verbose_name_plural': 'Históricos dos Planos'},
        ),
        migrations.AddField(
            model_name='desafiopdi',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='macroprocesso',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='objetivopdi',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
        migrations.AddField(
            model_name='risco',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em'),
        ),
    ]
