# Generated by Django 5.2.17 on 2026-09-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0008_add_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='latitude',
            field=models.FloatField(blank=True, db_column='latitude', null=True),
        ),
        migrations.AddField(
            model_name='risco',
            name='longitude',
            field=models.FloatField(blank=True, db_column='longitude', null=True),
        ),
    ]
