# Generated by Django 5.2.17 on 2026-09-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0009_risco_latitude_risco_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='endereco',
            field=models.CharField(blank=True, db_column='endereco', max_length=255, null=True),
        ),
    ]
