# Generated by Django 5.2.17 on 2026-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0010_risco_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='foto',
            field=models.ImageField(blank=True, db_column='foto', null=True, upload_to='monitoramentos/'),
        ),
    ]
