# Generated by Django 5.2.12 on 2026-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=255, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(db_column='sigla', max_length=20, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('siape', models.CharField(db_column='siape', max_length=20, unique=True, verbose_name='Matrícula SIAPE')),
                ('nome', models.CharField(db_column='nome', max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
                ('equipe', models.BooleanField(db_column='equipe', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('setores', models.ManyToManyField(blank=True, db_table='usuario_setores', related_name='usuarios', to='usuarios.setor', verbose_name='Setores do Usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
    ]
