# Generated by Django 5.2.12 on 2026-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_seed_setores_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['sigla_centro', 'nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(db_column='ativo', default=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='fonte_oficial',
            field=models.BooleanField(db_column='fonte_oficial', default=False, verbose_name='Importado de base oficial'),
        ),
        migrations.AddField(
            model_name='setor',
            name='nome_centro',
            field=models.CharField(blank=True, db_column='nome_centro', default='', max_length=255, verbose_name='Nome do Centro'),
        ),
        migrations.AddField(
            model_name='setor',
            name='sigla_centro',
            field=models.CharField(blank=True, db_column='sigla_centro', default='', max_length=20, verbose_name='Sigla do Centro'),
        ),
        migrations.AddField(
            model_name='setor',
            name='tipo_unidade',
            field=models.CharField(blank=True, db_column='tipo_unidade', default='', max_length=100, verbose_name='Tipo da Unidade'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='sigla',
            field=models.CharField(db_column='sigla', max_length=255, verbose_name='Sigla'),
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('nome', 'sigla_centro', 'tipo_unidade'), name='uniq_setor_nome_centro_tipo'),
        ),
    ]
