# Generated by Django 5.2.13 on 2026-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_add_uuid_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sem_equipe_desde',
            field=models.DateTimeField(blank=True, db_column='sem_equipe_desde', null=True),
        ),
    ]
